### ISSUE TITLE
Add shield emit point to shield units

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#101]
This is a minor modeling task. Add shield emit points to shield units and update unit script to reflect this. Nothing visually has to change, just add a point where the shield query can use.

**Comment by Sharkgamedev** [comment]
👍

**Comment by Sharkgamedev** [comment]
We'll see when I get around to this. I was originally off put by the idea that there was a large number of shield units but looking over it there are nowhere near as many then I had imagined, plus it takes roughly 10 seconds to add such to them.

**Comment by Arch-Shaman** [comment]
This doesn't seem to be too much of an issue in modern FW.
