### ISSUE TITLE
Add decloak turret

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#106]
This would be a stationary decloaker used to help cloaky v cloaky.  It would cost 10e to upkeep and cost in the 650 - 850m range.

**Comment by Sharkgamedev** [comment]
Do you already have a model in mind for this or is one required?

**Comment by Arch-Shaman** [comment]
I have a placeholder put in. I dont have a specific model in mind. Probably something radar looking?

**Comment by Sharkgamedev** [comment]
What about a stardust but replace the minigun with a radar dish?

**Comment by Arch-Shaman** [comment]
That could work. The weapondef currently works as a pulse so that'll be something to take into account.

**Comment by Sharkgamedev** [comment]
Has this been scrapped?

**Comment by Arch-Shaman** [comment]
No opening a separate issue for remodeling. Its implemented atm
