### ISSUE TITLE
Rampart fires occassionally when degridded

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#108]

**Comment by HTMLPhoton** [comment]
This happens because Rampart is missing a check during `script.aimWeapon` which Desolator and Lucifer both have. This check exists because the overdrive gadget doesn't update every frame.

Fixed in #110

**Comment by HTMLPhoton** [comment]
#110

**Comment by Arch-Shaman** [comment]
Merged into stable.
