### ISSUE TITLE
Deathclone for Caretaker and Rejuvenator

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#112]
Caretaker has no death clone which is out of place in zk. Adding it should be easy.

**Comment by Sharkgamedev** [comment]
Doing this today

**Comment by Arch-Shaman** [comment]
Possibly fixed by #131

**Comment by Arch-Shaman** [comment]
Confirm fix. Nicely done.
