### ISSUE TITLE
Desyncs

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#113]

**Comment by DiligentDolphin** [comment]
Upload gameplay log file. Thanks for the develop :-D
`uname -a`
`Linux localhost.localdomain 5.10.10-200.fc33.x86_64 #1 SMP Sun Jan 24 19:58:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux` 
[20210130073312_infolog.txt](https://github.com/Arch-Shaman/ZK-Futurewars-Mod/files/5898287/20210130073312_infolog.txt)

**Comment by Arch-Shaman** [comment]
Try deleting path cache (in game lobby -> lobby settings -> scroll down -> delete path cache)

**Comment by Arch-Shaman** [comment]
Setting to invalid as it seems this isn't our fault. Issue will remain open in case something comes up though. Something seems off here. Nothing code wise seems to be potentially desyncing (all gadget code is pretty much synced).

There current prevailing theory is either that you're morphing an invalid comm or pathing cache stuff.

**Comment by Arch-Shaman** [comment]
This has been resolved by downloading the source and self-packing with path cache clearing.
