### ISSUE TITLE
Make a better decloak CEG

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#134]

**Comment by Sharkgamedev** [comment]
I imagine whenever this does happen it could be a double or?

**Comment by Arch-Shaman** [comment]
Means the decloak tower needs a better ceg. Its pretty distracting with the shockwave

**Comment by Sharkgamedev** [comment]
Ah ok, I thought it meant the effect on units when they exit a cloak zone.

**Comment by Arch-Shaman** [comment]
We could probably create a ceg to play on units when they get decloaked by a decloak tower. But right now its functional.
