### ISSUE TITLE
Fix singularity missile buildpic

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#141]

**Comment by Sharkgamedev** [comment]
I think I might just give up with icon_generator.lua and just set it to a special background that's a flat color so I can cut it out in gimp and then rotate it.

**Comment by Arch-Shaman** [comment]
Thats an idea. However you see fit.

**Comment by Arch-Shaman** [comment]
@Sharkgamedev try it again now that I fixed singularity missile.

**Comment by Sharkgamedev** [comment]
Alright I'll try that tonight! What specifically do you mean by +90 degrees on x axis, and did you do that in the actual model or in the unitscript cause I can update the model and I'd feel better about the model being fixed than a fix being applied in the unitscript.

**Comment by Arch-Shaman** [comment]
It's okay, it's recoverable. A lot of people enjoy the wake though and nobody has brought up the buildpic so it's minor.

**Comment by Arch-Shaman** [comment]
As far as the rotation goes, it needs to be at -90 degrees and -40m on the Y axis. I've corrected this (the model works now in game) so now all you gotta do is regen the build pic and it should look okay.

**Comment by Arch-Shaman** [comment]
Seems fixed
