### ISSUE TITLE
Azimuth kills CPUs for some reason

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#157]
[5:50 PM] Inde_Irae: oh well, thats lame
[5:50 PM] Inde_Irae: Also, Luci laser kept killing everyones cpu
[5:50 PM] Inde_Irae: idk if you saw that
[5:50 PM] Inde_Irae: It would suddenly go bananas and be super bright and all that

**Comment by HTMLPhoton** [comment]
Do you by any chance have a link to the replay where this happened?

I think it might be becuase the gadget which spawns the explosion CEG runs in synced. so Azimuth spawns one CEG for every player there is. though I;m not sure if this is how spring handles the spawning of CEGs

**Comment by Arch-Shaman** [comment]
http://zero-k.info/Battles/Detail/1049379?ShowWinners=True

**Comment by Arch-Shaman** [comment]
Fair warning: this replay is nearly unwatchable.

**Comment by HTMLPhoton** [comment]
It turns out this is due to Azimuth not having a cap for how big the flare can get while force-firing at ground. A simple max check should do.

**Comment by HTMLPhoton** [comment]
#160 Should fix this

**Comment by Arch-Shaman** [comment]
Probably fixed by #160
