### ISSUE TITLE
Radar has retreat

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#175]

**Comment by HTMLPhoton** [comment]
NONSENSE!

MY RADARS SHALL KNOW NO RETREAT!

THEY SHALL , umm, idk, radar? THE ENEMY UNTIL THEY GET SNEEZED ON!

**Comment by Sharkgamedev** [comment]
> NONSENSE!
> 
> MY RADARS SHALL KNOW NO RETREAT!
> 
> THEY SHALL , umm, idk, radar? THE ENEMY UNTIL THEY GET SNEEZED ON!
> 
> Edit: prehaps it is because radars can morph into sparrows? I know that you can give move commands to Cornea, Radar and Aegis is base ZK

Not sure if it did get committed to stable but I changed base radar to morph into advanced a while back, so they can't morph into sparrow anymore. Unless adv can though I don't think so.

**Comment by Arch-Shaman** [comment]
Potentially fixed by 573e0db. Marked as 'Feedback needed'

**Comment by Arch-Shaman** [comment]
> Not sure if it did get committed to stable but I changed base radar to morph into advanced a while back, so they can't morph into sparrow anymore. Unless adv can though I don't think so.

It did get committed (See: afd0159) pretty early on.
