### ISSUE TITLE
RTG Corpse has weird colvol

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#184]
![image](https://user-images.githubusercontent.com/48730089/108928582-64586100-7610-11eb-80ec-2349a4e4a2ef.png)

**Comment by HTMLPhoton** [comment]
Clearly, this is not an issue with RTG corpse colvols, but rather an issue with it's death explosion not being strong enough

**Comment by Sharkgamedev** [comment]
> Clearly, this is not an issue with RTG corpse colvols, but rather an issue with it's death explosion not being strong enough. you see, dead units cannot get stuck

I agree somewhat. I think it could probably be mitigated by a change in y position but the only way to truly fix it would be to make its explosion strong enough to kill anything small enough to fit inside of it as @HTMLPhoton has suggested. How do they get in there in the first place? Just right next to it? Or did they actually walk in well after the fact?

**Comment by Arch-Shaman** [comment]
![image](https://user-images.githubusercontent.com/48730089/131765061-ffd2ba22-92a6-425f-9e62-d131020a8a50.png)
