### ISSUE TITLE
Commander Module Requirements are borked

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#196]
Eg: Flux amplifier no longer requires lightning gun.

**Comment by Arch-Shaman** [comment]
Note: the relevant changes were reverted in 20237895d4a707c808f39c4bd56690323d40f6b9 and 5e04c17.

**Comment by Arch-Shaman** [comment]
Note 2 regarding Knight commander weapons:
You need to enable these weapons in the dynamic comm config. Problem here is that there's a maximum of 32 weapons.

**Comment by HTMLPhoton** [comment]
Max weapons might be able to be circumvented but it would involve a lot of derpity derp

Those PRs didn't contain anything important, so simply reverting the changes should fix this

**Comment by Arch-Shaman** [comment]
Closed by revert. We'll revisit this at some point.
