### ISSUE TITLE
Hunt down the runtime debug message

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#197]
Something is sending a message during stable games with the following text:

target: <num> targetID: <num>

Find and eliminate this menace.

**Comment by Sharkgamedev** [comment]
> Something is sending a message during stable games with the following text:
> 
> target: targetID:
> 
> Find and eliminate this menace.

Isn't there some script where you can filter out such things?

**Comment by Arch-Shaman** [comment]
I dont know. Id prefer debug messages to be not present in infologs if possible in our release versions.
