### ISSUE TITLE
Touch Hovers this stable

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#207]
Some nice units we could hit up:
- [x] Dagger:
* Could potentially gain a rapid gauss gun or something.
- [x] Mace:
* Needs more DPS or armor or cost reduction. Maybe a nice shiny laser?
- [ ] Scalpel:
* It's pretty meh. Damage increase?

**Comment by HTMLPhoton** [comment]
Mace could do with an Azimuth laser

**Comment by Arch-Shaman** [comment]
Dagger -> Spear (via 5dac047)
* Heavier weight
* Gained gauss scattergun
* bonus effectivity vs shields
