### ISSUE TITLE
Make Dante Great Again

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#22]
Dante is an iconic strider. It should be quite exciting. Some ideas:

- Give it cluster napalm missiles
- Turn the heat ray into a heat laser
- Make it immune to fire.

**Comment by HTMLPhoton** [comment]
This is almost done

Dante will get 10 flamethrowers and 12 heatrays

The missiles just need a bit of polishing

**Comment by Arch-Shaman** [comment]
closed by d12de86 (i think)
