### ISSUE TITLE
Make Anti require grid

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#220]
* Require grid of 160 (it's two fusions at max capacity, which means you can't just instantly plop an anti and be done with it)
* Reduce cost
* Be unable to intercept nukes without grid.
* Have decent grid size (maybe 440? mostly for AI)

This will allow for other attack venues other than "shockley the anti then nuke" as well as making it more fun for players to play with the new supernuke.

**Comment by HTMLPhoton** [comment]
cost reduction is probably unnecessary due to the cost of stockpiling an oblivion shot

**Comment by Arch-Shaman** [comment]
Done: 9f3623c
