### ISSUE TITLE
Toad is a bit insane

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#224]
I've had the missiles pull a krow across the map before. Maybe we should turn them into a newton pull beam?

**Comment by HTMLPhoton** [comment]
Question: do you mean the missiles chased a krow across the map or the missiles yeeted a krow across the map?

**Comment by Arch-Shaman** [comment]
Yeeted it across the map, as well as most gunships. A sustained gun like newton would be a bit more usable (maybe even as a flex weapon? lol)

**Comment by Arch-Shaman** [comment]
Seems fine now. We added some impulse to the main beam in indev and it looked fine.
