### ISSUE TITLE
Fix projectilly spawned units gaining awards

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#269]
![image](https://user-images.githubusercontent.com/48730089/119384845-48a63a80-bc93-11eb-8606-b693c5268d6c.png)

**Comment by HTMLPhoton** [comment]
did it hit a starlight or something?

**Comment by Arch-Shaman** [comment]
No?

**Comment by HTMLPhoton** [comment]
Should be fixed now

**Comment by Arch-Shaman** [comment]
We'll see in the next batch of testing I think.

**Comment by Arch-Shaman** [comment]
Seems fixed.
