### ISSUE TITLE
The OOM demon is upon us.

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#275]
![image](https://user-images.githubusercontent.com/48730089/119975345-bdbf8b80-bf83-11eb-9c02-db2379ad5a24.png)

**Comment by Sharkgamedev** [comment]
😱😱


This is top priority!
Scramble the defenses!

Maybe it's something to do with the uvs/texture? I'll have a look tonight.

**Comment by Arch-Shaman** [comment]
ITS DEAD! killed by 0c4a142
