### ISSUE TITLE
Stardust Redesign Ideas

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#28]
Stardust:
- Requires grid (8 or 10 energy)
+ Gains canister rounds
+ more range (or overshoot maybe?)

**Comment by Sharkgamedev** [comment]
I say overshoot over range here.

**Comment by Arch-Shaman** [comment]
An idea for it could be to gain RoF as more energy is put into the grid see: #24
