### ISSUE TITLE
Yet another OOM demon takes its place

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#282]
[f=0028679] Error: [LuaRules::RunCallInTraceback] error=4 (LUA_ERRMEM) callin=AllowCommand trace=[Internal Lua error: Call failure] not enough memory

**Comment by Sharkgamedev** [comment]
When is this caused?

**Comment by Arch-Shaman** [comment]
closed by f99ea81 apparently

**Comment by Arch-Shaman** [comment]
We don't know what causes it but it was fixed by moving the sleep out of a conditional statement.
