### ISSUE TITLE
Advance Radar

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#29]
* Have Advanced Radar morph from basic radar.
* Remove advanced radar from build options.
* Make Advanced Radar do something useful (Maybe give it longer vision, jammer, and allow it to paint targets for heavy artillery like a spotter of some sort.)

**Comment by Sharkgamedev** [comment]
To keep with ideas for #24 what about more power for more range?

**Comment by Arch-Shaman** [comment]
That'd work. Radar Overdrive.

**Comment by Sharkgamedev** [comment]
Do you think it should just have radar overdrive or also expensive target 'spotting' and potentially jamming.

**Comment by Arch-Shaman** [comment]
I've touched adv radar in 14fe640 and 10d0fc0 to push it into the spotter role, as well as standardize its morph time to morph at 10m/s. It now provides both sight and sonar.

**Comment by Sharkgamedev** [comment]
> * Have Advanced Radar morph from basic radar.
> * Remove advanced radar from build options.
> * Make Advanced Radar do something useful (Maybe give it longer vision, jammer, and allow it to paint targets for heavy artillery like a spotter of some sort.)

Latest release solves number 3 with it's change of making Artillery reveal themselves while firing.

**Comment by Arch-Shaman** [comment]
Let's close this and make a new issue for additional radar interactions.
