### ISSUE TITLE
Improve default behavior of MIRV weapons (namely scylla)

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#293]
Ideas:
* Pentagon shape
* Default all at one position
* Circle spread tightened

**Comment by HTMLPhoton** [comment]
imho it should be configured through customparam. untargeted shots should be spread out in a polygonal shape if there are more than 3, and randomly spread if there are 2 or less. the range at which untargeted shots would be spread over should be confirgured in the customparams

**Comment by Arch-Shaman** [comment]
sounds good to me.
