### ISSUE TITLE
Apply ai_resourcecheat only to teams with no humans

### ISSUE THREAD

**Issue by discon-nected** [Arch-Shaman/ZK-Futurewars-Mod#296]
If there are AIs on the human team, human players benefit from `ai_resourcecheat` due to shared metal, which effectively nullifies it's intent. Would be good to only apply to teams without any humans if possible. This would help to balance Human+AI vs AI games.

**Comment by Arch-Shaman** [comment]
I'll push a fix for this tonight probably.

**Comment by discon-nected** [comment]
Great

Didn't know about a handicap system. Will look that up.

**Comment by Arch-Shaman** [comment]
'resource_handicap' is the name. it would work like this:
!setoptions resource_handicap =1 1.25, <other modoptions>

with this in mind is this necessary? discoverability would be better probably.

**Comment by discon-nected** [comment]
It would still be nice but if you think it might interfere with things then better not to mess with it.
How do I know a player's number for use with `resource_handicap`?

**Comment by Arch-Shaman** [comment]
it's ally team. team 1 is first then team 2 then so on.

**Comment by discon-nected** [comment]
OK, so it's team wide. That solves my problem. Closing this issue now. Thank you!

**Comment by Arch-Shaman** [comment]
No problem. I wished chobby had support for modoptions changes.

**Comment by discon-nected** [comment]
Is that on the roadmap?

**Comment by Arch-Shaman** [comment]
No idea. I'll probably take a crack at it.
