### ISSUE TITLE
Commander shields are busted

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#332]
* Personal shield doesn't charge at all on its own.
* Area shield stops at 3600 (old value)

i do suspect that #129 is doable through https://github.com/ZeroK-RTS/Zero-K/blob/ef48ebb2d4f59627b865abbe5584bef6e07b67cb/LuaRules/Gadgets/unit_commander_upgrade.lua#L699 this

**Comment by Arch-Shaman** [comment]
For more info: this regression occurred between b3852ee (RC-9) and bf18adc (RC-8), which means that it was caused by 359a1f8 and 99ac8e7 as e0e14fd was reverted on develop and did not change the bug's status. This leads me to suspect that these values are hardcoded somewhere or messed with somewhere..

**Comment by IdkSomethingTemporary** [comment]
Cannot repro and probably long dead
