### ISSUE TITLE
Redesign Mogul or fix it up

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#340]
Long range laser guidance doesn't work properly for it, and it's kinda not as creative as other things.

**Comment by IdkSomethingTemporary** [comment]
The guidance seems to work perfectly fine from a code perspective AFAIK, however the AI **really** sucks at using it and brain dead humans not much better. Should we re-tool this into another frontline strider or a more of a support role?
Some ideas for new role:

- Battle-Artillery (Like, artillery but meant to front-line. may be impossible to get right, or it may work)
- Repair strider? (might fit reef more though...)
- Demi-Detris / Land nebula
- Artillery Strider, but easier to use

**Comment by Arch-Shaman** [comment]
Laser guidance could do with "go to last position lased" instead, maybe. Or a tag to do that.

**Comment by IdkSomethingTemporary** [comment]
Current mogul looks to be fine. closed until furthur incidents
