### ISSUE TITLE
Overclaim Prevention default

### ISSUE THREAD

**Issue by discon-nected** [Arch-Shaman/ZK-Futurewars-Mod#349]
Overclaim Prevention is a bit annoying. The default should be off, at least for AI. This AI is doomed...

![OverclaimPrevention](https://user-images.githubusercontent.com/20234985/132938982-e526bdbd-ef17-4849-888d-6c2a9ab8bf88.gif)

Isn't overclaim distributed to allies anyway?

**Comment by Arch-Shaman** [comment]
AFAIK there was some demand for ORP. I am testing a disable feature by default though.

**Comment by Arch-Shaman** [comment]
fixed in b8c60d4 by adding an option in Unit Behavior/default states to disable it by default.

**Comment by discon-nected** [comment]
TY. I usually want to overclaim wrecks to prevent the enemy from consuming them.
