### ISSUE TITLE
Merlin rockets hit Nebula shield crash

### ISSUE THREAD

**Issue by KramNoslo** [Arch-Shaman/ZK-Futurewars-Mod#403]
For some players, when a Marlin fires its rockets at a target and the Nebula's shields is in the way, a crash may occur
For a few others it does not let the players who crashed rejoin the fight, instead they keep crashing at the same spot
[infolog.txt](https://github.com/Arch-Shaman/ZK-Futurewars-Mod/files/9075854/infolog.txt)

**Comment by Arch-Shaman** [comment]
Feedback needed -> Closed due to no complaints lately.
