### ISSUE TITLE
Figure out the AOE of CAS weapons

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#45]
Some method of figuring out the average spread of CAS weapons should be done and the unitdefs updated accordingly.

**Comment by HTMLPhoton** [comment]
(NOTE: this is not a good first issue, this is likely involves an ungodly amount of math or a lot of brute-forcing)

**Comment by Arch-Shaman** [comment]
This is also a pretty minor thing. Probably not needed. We will see.

**Comment by Arch-Shaman** [comment]
Not needed probably, closing.
