### ISSUE TITLE
Make changes to make use of 08d50c8's improved efficiency

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#503]
https://github.com/ZeroK-RTS/Zero-K/commit/08d50c8ca4ad720d3821f143d55fd81ee03ee27c

**Comment by sprunk** [comment]
Technically there is no compatibility changes required, everything is supposed to keep working. I don't expect to remove support for the old method, the new one is just more efficient.

**Comment by Arch-Shaman** [comment]
Closed as this seems to have been implemented.
