### ISSUE TITLE
Gunshipcon in wake

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#542]
Gunshipcons in singularities sometimes get thrown into the stratosphere and cannot crash in a reasonable time.

**Comment by IdkSomethingTemporary** [comment]
Same also happens for planecon, maybe make crashing units just get destroyed after, say, 10s?

**Comment by Arch-Shaman** [comment]
Closing as it seems to be fixed since the aircrash update. Feel free to reopen
