### ISSUE TITLE
Make chainlightning not target features

### ISSUE THREAD

**Issue by IdkSomethingTemporary** [Arch-Shaman/ZK-Futurewars-Mod#551]
The targeting of features creates a lrage amount of visual noise and probably a not insignificant amount of lag.
Should be easy enough to disable if I get the go ahead ^w^

**Comment by Arch-Shaman** [comment]
Just add "chainlightning_donttargetfeature" to CP.

**Comment by Arch-Shaman** [comment]
Iirc this issue was resolved with last pr. Closing, feel free to open if it's in error.
