### ISSUE TITLE
Liberator does exactly what it says on the tin

### ISSUE THREAD

**Issue by luminaStuffphoton** [Arch-Shaman/ZK-Futurewars-Mod#552]
**Unit**: Liberator (staticheavyarty)
**Problem**: Liberator is really good at liberating you from stalemates, so good in fact that there's no point to even build anything more expensive because Liberator will usually just win the game for 10k if it's in the hands of a good player.
**Replays** http://zero-k.info/Battles/Detail/1711310 is just liberator carrying. http://zero-k.info/Battles/Detail/1705115, http://zero-k.info/Battles/Detail/1705074,  http://zero-k.info/Battles/Detail/1705067 and http://zero-k.info/Battles/Detail/1705061 were a combination of liberator and nuke
**Suggestion** Unsure >w<. Prehaps liberator, superstriders and superweapons all need to be rethought, with the price of the latter toned down quite heavily in combination with more agressive global reveal (see #545 ). Liberator definitely needs a nerf though.  just not sure what needs nerfing, likely range and dps at once

**Comment by Arch-Shaman** [comment]
Maybe try nerfing the SWOD a bit?

**Comment by IdkSomethingTemporary** [comment]
acutally, maybe buffing the swod but nerfing the rof is better. the current issue is that lib rush is too good. increasing the e cost or the swod but decreasing the rof would make early libs a lot worse

**Comment by Arch-Shaman** [comment]
Nerfed recently, reopen if still op.
