### ISSUE TITLE
A few Widget Issues

### ISSUE THREAD

**Issue by IdkSomethingTemporary** [Arch-Shaman/ZK-Futurewars-Mod#557]
**Resign State**:
Error: [LuaUI::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UpdatePlayer trace=[Internal Lua error: Call failure] [string "LuaUI/Widgets/gui_resignstate.lua"]:123: attempt to index field '?' (a nil value)
Error: [LuaUI::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UpdatePlayer trace=[Internal Lua error: Call failure] [string "LuaUI/Widgets/gui_resignstate.lua"]:121: attempt to index field '?' (a nil value)
**Economic View**
Error: gl.CreateList: error(2) = [string "LuaRules/Utilities/glVolumes.lua"]:270: bad argument #1 to 'Translate' (number expected, got nil)
Error: gl.CreateList: error(2) = [string "LuaRules/Utilities/glVolumes.lua"]:270: bad argument #1 to 'Translate' (number expected, got nil)
[cawidgets.lua] Error: Error in DrawWorld(): [string "LuaUI/Widgets/gui_showeco_action.lua"]:506: bad argument #1 to 'Translate' (number expected, got nil)
[cawidgets.lua] Error: Removed widget: Showeco and Grid Drawer
Error: DrawWorld: OpenGL stack check error, matrix mode = GL_MODELVIEW, depth = 1, please make sure to pop all matrices before end

**Comment by Arch-Shaman** [comment]
Resign state is now dead as of e5097416. Ecoview should be addressed as well.
