### ISSUE TITLE
Deserter and Hades Missiles have issues

### ISSUE THREAD

**Issue by IdkSomethingTemporary** [Arch-Shaman/ZK-Futurewars-Mod#558]
Deserter Anti-ground missiles need a lot more homing and fire arc. currently they have trouble firing
Deserter and Hades AA missiles have a tendancy to lag the game in large numbers

**Comment by Arch-Shaman** [comment]
Probably needs to be lowered a bit in numbers while keeping stats. Maybe
hades needs something instead of missiles?
