### ISSUE TITLE
Make Anti-Nukes all deploy when a nuke is launched

### ISSUE THREAD

**Issue by Arch-Shaman** [Arch-Shaman/ZK-Futurewars-Mod#60]
> I'm not that happy with how antinukes deploy as soon as the nuke is launched. It feels like too much information and is fairly hidden. I would rather have them only deploy just before they fire. Alternately, every single antinuke on the map could be made to deploy whenever a nuke is launched, just in case.

This would be a joint improvement with ZKDev.

**Comment by Sharkgamedev** [comment]
I'm not sure what this neccercarily means? Having all antinukes fire at one nuke means even if you have 5 antinukes they can be overwhelmed by the launch of two miles from the enemy which is not desirable imo. If your just talking about making the 'silos' open usually across all anti nukes I thought this was something that already occured? Silos open even if they are not the ones that launch. Other than that is it just visually delaying the opening of silos?

**Comment by Arch-Shaman** [comment]
Deploy is the stage before firing. It just makes it ready to deploy. Currently the one selected to be the interceptor is deployed.

**Comment by Arch-Shaman** [comment]
This is already taken care of since 0.20.0's rework of antinukes, rendering this issue obsolete.
