### ISSUE TITLE
Widget Crash

### ISSUE THREAD

**Issue by shadoxxhd** [Arch-Shaman/ZK-Futurewars-Mod#634]
**Description of bug**: the "gui_chilli_selections_and_cursortips.lua" widget keeps crashing multiple times per game
**Version Encountered in**: prerelease version
**Modoptions, if any**: custom tweakdefs script

**Infolog**: 
````
[t=03:34:11.836036][f=0024301] [cawidgets.lua] Error: Error in Update(): [string "LuaUI/Widgets/gui_chili_selections_and_cursortip.lua"]:2115: attempt to compare number with nil
[t=03:34:11.836079][f=0024301] [cawidgets.lua] Error: Removed widget: Chili Selections & CursorTip v2
````

The line is now 2123 after Commit 8c7bb32  (`if progress >= 1 then`); there should probably be a nil check there as well.

**Comment by Arch-Shaman** [comment]
Fixed via https://github.com/Arch-Shaman/ZK-Futurewars-Mod/commit/c9bb75a8f91c6f96a5aee8597c1abcd50bcb8e4a
